#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10
TOTAL_MINUTES=70

# Roda a partir da pasta advisor-platform/. O .env de referência é o da raiz do repo.
cd "$(dirname "$0")"
ENV_FILE="../.env"

REF=""            # SUPABASE_PROJECT_REF, lido do .env da raiz
SUPA_URL=""       # https://<ref>.supabase.co
PAGES_URL=""      # URL pública da plataforma (Cloudflare Pages)

# sb_secret NOME VALOR — grava um segredo da Edge Function no projeto remoto.
sb_secret() {
  if supabase secrets set "$1=$2" --project-ref "$REF" >/dev/null 2>&1; then
    printf '  %s✓ segredo%s %s no Supabase\n' "$GREEN" "$RESET" "$1"
  else
    SKIPPED+=("segredo $1 (rode: supabase secrets set $1=... --project-ref $REF)")
    warn "não consegui gravar o segredo $1 — faça manualmente depois"
  fi
}

banner "Deploy da plataforma das consultoras (ticket 037)"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Pré-requisitos" 4
say "Confere as ferramentas e lê o project ref do .env da raiz."
for c in supabase node npm; do
  if command -v "$c" >/dev/null 2>&1; then step "$c: ok"; else
    warn "falta '$c' no PATH — instale antes de seguir"; fi
done
REF=$(grep -E '^SUPABASE_PROJECT_REF=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- | tr -d '\r')
if [[ -z "$REF" ]]; then
  ask REF "SUPABASE_PROJECT_REF (Project Settings > General):"
fi
SUPA_URL="https://${REF}.supabase.co"
note "projeto: $REF   ($SUPA_URL)"
pause "Enter para começar"

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Supabase — link e migração" 8
say "Cria a tabela handoffs, os enums, a advisor_allowlist e as políticas RLS."
step "Vai pedir a senha do banco (SUPABASE_DB_PASSWORD do .env)."
supabase link --project-ref "$REF" || warn "link falhou — confira token/senha e rode de novo"
if confirm "Aplicar as migrações agora (supabase db push)?"; then
  supabase db push || warn "db push falhou — veja a saída acima"
fi
note "Confira no painel: Table editor > handoffs e advisor_allowlist devem existir."
pause "Enter quando as tabelas aparecerem"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Allow-list — os 4 e-mails reais" 6
say "Quem pode entrar na plataforma. Use as contas @gmail.com que elas usam no celular."
ask ADV1 "E-mail da 1ª consultora:";  ask NAME1 "Nome dela (como aparece na fila):"
ask ADV2 "E-mail da 2ª consultora:";  ask NAME2 "Nome dela:"
ask ADV3 "E-mail da 3ª consultora:";  ask NAME3 "Nome dela:"
ask ADV4 "E-mail da dona:";           ask NAME4 "Nome dela:"
cat > /tmp/advisor-allowlist.sql <<SQL
delete from advisor_allowlist where email like 'placeholder%';
insert into advisor_allowlist (email, name) values
  ('${ADV1,,}', '${NAME1}'),
  ('${ADV2,,}', '${NAME2}'),
  ('${ADV3,,}', '${NAME3}'),
  ('${ADV4,,}', '${NAME4}')
on conflict (email) do update set name = excluded.name;
SQL
note "SQL gerado em /tmp/advisor-allowlist.sql"
open_url "https://supabase.com/dashboard/project/${REF}/sql/new"
step "Cole o conteúdo de /tmp/advisor-allowlist.sql no SQL Editor e rode (Run)."
pause "Enter quando rodar sem erro"

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Resend — e-mail de aviso" 10
say "O aviso de chamado novo sai por aqui. Plano free: 100 e-mails/dia."
open_url "https://resend.com/api-keys"
step "Crie uma API key (permissão 'Sending access'). Copie."
ask_secret RESEND_API_KEY "Cole a RESEND_API_KEY:"
open_url "https://resend.com/domains"
say "Para o 'from' você precisa de um domínio verificado."
if confirm "Já tem um domínio verificado no Resend?"; then
  ask NOTIFY_FROM "Endereço de envio (ex: Fila Lais Casa <fila@seudominio.com>):"
else
  warn "Sem domínio: use 'onboarding@resend.dev' — só entrega no e-mail dono da conta Resend."
  NOTIFY_FROM="Fila Lais Casa <onboarding@resend.dev>"
  note "Troque depois de verificar o domínio: supabase secrets set NOTIFY_FROM=..."
fi
NOTIFY_TO="${ADV1},${ADV2},${ADV3},${ADV4}"
sb_secret RESEND_API_KEY "$RESEND_API_KEY"
sb_secret NOTIFY_FROM "$NOTIFY_FROM"
sb_secret NOTIFY_TO "$NOTIFY_TO"
pause "Enter para seguir"

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Cloudflare Pages — publicar a tela" 12
say "Build da SPA e publicação estática (free). A URL sai daqui."
( cd web && npm install && VITE_SUPABASE_URL="$SUPA_URL" \
    VITE_SUPABASE_PUBLISHABLE_KEY="$(grep -E '^SUPABASE_PUBLISHABLE_KEY=' "$ENV_FILE" | cut -d= -f2- | tr -d '\r')" \
    npm run build ) || warn "build falhou — veja acima"
open_url "https://dash.cloudflare.com/?to=/:account/pages/new"
step "Pages > Create > Connect to Git (repo Agente-lais) OU 'Direct upload'."
step "Se Connect to Git: Framework preset = None; Build command = 'npm run build';"
step "  Build output directory = 'advisor-platform/web/dist'; Root directory = 'advisor-platform/web'."
step "Em Settings > Environment variables, adicione:"
note "  VITE_SUPABASE_URL = $SUPA_URL"
note "  VITE_SUPABASE_PUBLISHABLE_KEY = (a publishable key do .env)"
step "Se Direct upload: suba a pasta advisor-platform/web/dist que o build acabou de gerar."
ask PAGES_URL "URL pública que a Pages deu (https://...pages.dev):"
write_env ADVISOR_PLATFORM_URL "$PAGES_URL"
sb_secret ADVISOR_PLATFORM_URL "$PAGES_URL"
pause "Enter quando a página abrir (vai dar erro de login — normal, ainda falta o Google)"

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Google — OAuth client" 10
say "É o 'Entrar com o Google'. Precisa de um projeto no Google Cloud."
open_url "https://console.cloud.google.com/apis/credentials/consent"
step "OAuth consent screen: User type = External. Preencha nome do app e e-mail."
step "Em 'Test users', adicione os 4 e-mails da allow-list (ou publique o app)."
open_url "https://console.cloud.google.com/apis/credentials"
step "Create credentials > OAuth client ID > Application type = Web application."
step "Authorized redirect URIs: adicione exatamente:"
note "  ${SUPA_URL}/auth/v1/callback"
step "Create. Copie o Client ID e o Client secret."
ask GOOGLE_CLIENT_ID "Cole o Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Cole o Client secret:"
write_env SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET "$GOOGLE_CLIENT_SECRET"
pause "Enter para configurar no Supabase"

# ── 7 ────────────────────────────────────────────────────────────────────
stage "Supabase Auth — ligar o Google" 6
open_url "https://supabase.com/dashboard/project/${REF}/auth/providers"
step "Providers > Google > Enable. Cole o Client ID e o Client secret. Save."
open_url "https://supabase.com/dashboard/project/${REF}/auth/url-configuration"
step "Site URL = $PAGES_URL"
step "Redirect URLs: adicione  ${PAGES_URL}/**  e  http://localhost:5173/**"
pause "Enter quando salvar os dois"

# ── 8 ────────────────────────────────────────────────────────────────────
stage "Edge Function — deploy + segredo do webhook" 6
WEBHOOK_SECRET=$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32)
note "segredo do webhook gerado: $WEBHOOK_SECRET  (você vai colar no passo 9)"
sb_secret HANDOFF_WEBHOOK_SECRET "$WEBHOOK_SECRET"
supabase functions deploy notify-handoff --project-ref "$REF" \
  || warn "deploy da função falhou — veja acima"
printf '%s' "$WEBHOOK_SECRET" > /tmp/handoff-webhook-secret.txt
note "cópia do segredo em /tmp/handoff-webhook-secret.txt"
pause "Enter para criar o webhook"

# ── 9 ────────────────────────────────────────────────────────────────────
stage "Database Webhook — INSERT em handoffs" 5
open_url "https://supabase.com/dashboard/project/${REF}/database/hooks"
step "Create a new hook:"
note "  Name: notify-handoff"
note "  Table: public.handoffs   ·   Events: Insert"
note "  Type: HTTP Request   ·   Method: POST"
note "  URL: ${SUPA_URL}/functions/v1/notify-handoff"
step "HTTP Headers: adicione  x-handoff-secret  com o valor de /tmp/handoff-webhook-secret.txt"
step "Create hook."
pause "Enter para o teste final"

# ── 10 ───────────────────────────────────────────────────────────────────
stage "Teste de ponta a ponta" 5
say "Insere um chamado de teste, confirma na tela + e-mail, e apaga."
open_url "https://supabase.com/dashboard/project/${REF}/sql/new"
step "Rode no SQL Editor:"
note "  insert into handoffs (contact_phone, contact_name, summary, engagement_mode, \"trigger\")"
note "  values ('+55 69 99999-0000', 'TESTE', 'Chamado de teste do wizard', 'consumer', 'qualified');"
step "Abra $PAGES_URL, entre com um dos e-mails da allow-list — o card 'TESTE' deve aparecer."
step "Confira se o e-mail de aviso chegou nas 4 caixas."
step "Assuma e feche o card na tela para ver o fluxo todo."
if confirm "Deu tudo certo? (limpa o chamado de teste)"; then
  step "Rode:  delete from handoffs where contact_name = 'TESTE';"
fi
pause "Enter para finalizar"

finish
note "Plataforma: $PAGES_URL"
note "Ainda placeholder até o runtime do agente existir: o INSERT real de chamado (ticket 031)."
